import numpy as np
from tracking.filters.kalman import KalmanFilter
from fusion.filters.ukf import UnscentedKalmanFilter, sigma_points
from tracking.models.measurement import LinearPosition2D
from tracking.models.motion import ConstantVelocity2D


def test_sigma_points_reconstruct_moments():
    """
    Test that the sigma points generated by the Unscented Kalman Filter can reconstruct the original mean and covariance.
    Assert that the reconstructed mean and covariance are close to the original.
    """

    # Define a state vector and covariance matrix
    x = np.array([1.0, 2.0, 3.0]) # Randomly chosen by me
    P = np.array([[0.1, 0.0, 0.0],
                  [0.0, 0.2, 0.0],
                  [0.0, 0.0, 0.3]]) # Randomly chosen by me

    # UKF parameters
    alpha = 1e-3
    beta = 2.0
    kappa = 0.0

    # Generate sigma points and weights
    points, Wm, Wc = sigma_points(x, P, alpha, beta, kappa)

    # Reconstruct mean and covariance from sigma points
    x_reconstructed = Wm @ points
    P_reconstructed = np.zeros_like(P)
    for i in range(points.shape[0]):
        diff = points[i] - x_reconstructed
        P_reconstructed += Wc[i] * np.outer(diff, diff)

    # Assert that the reconstructed mean and covariance are close to the original (x and P respectively)
    assert np.allclose(x_reconstructed, x, atol=1e-9), "Reconstructed mean does not match original"
    assert np.allclose(P_reconstructed, P, atol=1e-9), "Reconstructed covariance does not match original"

def test_ukf_matches_kf_on_linear_model():
    """
    Test that the Unscented Kalman Filter behaves like a standard Kalman Filter (KF)
    Assert that both output same x and P
    """

    dt = 0.1
    n_steps = 100
    x0_true = np.array([0, 0, 1, 1]) # px, py, vx, vy

    # Constant-velocity trajectory
    times = np.arange(n_steps) * dt

    trajectory = np.column_stack([
        x0_true[0] + x0_true[2] * times,
        x0_true[1] + x0_true[3] * times,
        np.full(n_steps, x0_true[2]),
        np.full(n_steps, x0_true[3]),
    ])

    # Filter setup
    motion_model = ConstantVelocity2D(sigma_a=0.0) # No process noise
    measurement_model = LinearPosition2D(sigma_pos=1e-6) # Small measurement noise to avoid errors in the Kalman gain calculation

    x0_filter = np.array([.5, .3, 5, 10]) # Initial state uncertainty (random numbers I've chosen)
    P0 = np.array([[10, 0, 0, 0], 
                   [0, 12, 0, 0], 
                   [0, 0, 34, 0], 
                   [0, 0, 0, 35]]) # Initial uncertainty (random numbers I've chosen)

    kf = KalmanFilter(motion_model, measurement_model, x0=x0_filter, P0=P0)
    ukf = UnscentedKalmanFilter(motion_model, measurement_model, x0=x0_filter, P0=P0)

    # Test KF vs UKF on linear model
    for i in range(1, n_steps):
        kf.predict(dt)
        kf.update(trajectory[i][:2])

        ukf.predict(dt)
        ukf.update(trajectory[i][:2])

        # Check that the state estimates and covariance matrices are close (1e-8 as the tolerance because UKF is more sensitive to numerical errors than EKF)
        assert np.allclose(kf.x, ukf.x, atol=1e-8), f"KF and UKF state estimates differ at step {i}"
        assert np.allclose(kf.P, ukf.P, atol=1e-8), f"KF and UKF covariance estimates differ at step {i}"

# To run: pytest tests/test_ukf.py -v